# 全局设置
Options:
  # 语言
  Language: "zh_CN"
  # 配置文件版本
  Config-Version: 1
  # 检查版本更新
  Check-Update: true
  # OP 版本更新通知
  OP-Notify: true
  # 启用 bStats 统计
  Send-Metrics: true
  # 启用调试模式
  Debug: false

# 物品设置
Item:
  # 物品库插件
  Plugin:
    - "MythicMobs"

# NBT 设置
NBT:
  # NBT 过滤器
  Filter:
    - "display"
    - "Damage"
    - "ench"
    - "Enchantments"
    - "Unbreakable"
    - "HideFlags"
    - "BlockEntityTag"
    - "Potion"